version: '3'
services:
    web:
      image: rmstrial/web
      build:
        context: ./server
        dockerfile: web.dockerfile
      volumes:
        - ./server:/usr/src/app
      network_mode: service:db
      depends_on:
        - db 
    db:
      image: postgres
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=example
          - POSTGRES_DB=userdb
      ports:
          - "5432:5432"
          - "3001:3001"
      build:
        context: ./database
        dockerfile: db.dockerfile
      volumes:
          - ./database:/docker-entrypoint-initdb.d
    front:
      image: rmstrial/front
      build:
        context: ./client
        dockerfile: front.dockerfile
      command: npm run serve
      volumes:
        - ./client:/app
      ports:
        - "8080:8080"
      

